apiVersion: v1
kind: Pod
metadata:
  name: pod-w-message2
spec:
  containers:
  - name: messager
    image: "ubuntu:14.0498948028904820840238"
    command: ["/bin/sh","-c"]
    args: ["sleep 60 && /bin/echo Sleep expired > /dev/termination-log"]
