apiVersion: v1
kind: Pod
metadata:
  name: ian-pv-pod
spec:
  volumes:
    - name: ian-pv-storage
      persistentVolumeClaim:
        claimName: ian-pvc
  containers:
    - name: ian-pv-container
      image: nginx
      ports:
        - containerPort: 80
          image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: ian-pv-storage

